# Generated by Django 5.2 on 2025-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
