# Generated by Django 5.2 on 2025-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_student_branch_student_field_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="establishment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="id_individual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="uuid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
