# Generated by Django 5.2 on 2025-04-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_is_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("improved_description", models.TextField(blank=True, null=True)),
                ("idea_score", models.FloatField(default=0.0)),
                ("suggestions", models.TextField(blank=True, null=True)),
                ("admin_approved", models.BooleanField(default=False)),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
